
== Signals

[[signal_format]]

SDL signals exchanged between agents, as well as those generated by <<_timers, timers>>,
are Lua tables whose first array element (i.e. the element with numeric key=_1_) is
a string and denotes the *signal name*. For example:

[source,lua,indent=1]
----
mysignal = { "MYSIGNAL", "hello", 1, 2, 3, self_, true }
----

Here _"MYSIGNAL"_ is the signal name while the other values are content information
(the example uses only array elements, but the record part of the
table can also be used).

Signals are *sent by reference*, which means that the receiving agent gets a reference
to the same table that was sent by the sender (not a copy).

Besides expecting the signal name as the first array element, MoonAgents makes no
other assumptions regarding the format and meaning of signals and of their contents: it just
delivers them between agents.

To send signals, agents use the following functions:

[[send]]
* _now_ = *send*(<<signal_format, _signal_>>, _dstpid_, [_priority_]) +
[small]#Sends _signal_ to the agent identified by _dstpid_, with the specified
_priority_, and returns the current <<_system_time,time>>. +
_priority_ is an integer between _1_ (high) and _N_ (low), where _N_ is the <<set_priority_levels, number of priority levels>>. +
If _priority_ is not specified, or if it is greater than _N_, the signal is sent without priority (which means lowest). +
This function is available both to agents and to the application, that can use it to send signals to the system.#

[[send_out]]
* _now_ = *send_out*(<<signal_format, _signal_>>) +
[small]#Sends _signal_ out to the application (this is equivalent to _send(signal, 0)_). +
Signals addressed to the application are sent out immediately (without scheduling) and synchronously. +
To receive signals sent to it, the application must set a non-blocking callback function
using <<set_receive_callback, set_receive_callback>>( ). +
This function is available only to agents.#

[[time_triggered_signals]]
Agents and the application can also schedule signals (*time-triggered signals*
footnote:[The *time-triggered signal* construct is not part of the SDL standard.
It is inspired by a proposal contained in the paper "`Real-time signaling in SDL`",
by M. Krämer, T. Braun, D. Christmann and R. Gotzhein, published in _SDL'11
Proceedings of the 15th international conference on Integrating System and
Software Modeling_, Springer-Verlag, 2011.]) to be
sent at a point in time in the future, without the need to create timers for this purpose:

[[send_at]]
* *send_at*(<<signal_format, _signal_>>, _dstpid_, _at_, [_maxdelay_]) +
[small]#A signal sent with this function  is retained in an internal queue and
dispatched (with maximum priority) to the agent identified by _dstpid_ only when the
<<_system_time, point in time>> given by _at_ arrives.
If, for some reason, the signal can not be delivered before the point in time given by
_at+maxdelay_, it is considered stale and silently discarded
(_maxdelay_ defaults to _infinity_, i.e. the signal is never considered stale).#

An agent can impose the priority of input signals by using this function:

[[input_priority]]
* *input_priority*(_signame_, [_priority_]) +
[small]#Set or cancel the imposed priority for _signame_ input signals. +
If _priority_ is an integer between _1_ (high) and _N_ (low), where _N_ is the
<<set_priority_levels, number of priority levels>>, then any _signame_ signal addressed
to this agent will be sent with that _priority_, no matter what specified by the sender. +
If _priority=nil_, any previously set priority for _signame_ signals is cancelled, and
the priority specified by the sender applies. +
Signals that are already sent but not yet dispatched at the time this function is called are not affected.
Signals generated by <<_timers, timers>>, as well as <<time_triggered_signals,time-triggered signals>>
and <<restore, re-scheduled signals>> are not affected either. +
This function is available only to agents.#
 
//(beware of subtle differences with the standard SDL priority input construct) @@

Using the following, an agent can save input signals so to receive them again at its next
change of state, or when it explicitly decides to:

[[save]]
* *save*( ) +
[small]#Saves the current input signal (i.e. the content of the 
*_$$signal_$$_* <<_special_variables, special variable>>) in the agent's _saved queue_, for later
re-scheduling. +
Saved signals are automatically re-scheduled when the agent <<next_state, changes its state>>,
and can be re-scheduled explicitly with <<restore,restore>>( ). +
This function is available only to agents and should be used only within transitions.#

[[restore]]
* *restore*( ) +
[small]#Re-schedules all the signals currently <<save, saved>> by the agent.
A state change has the same effect. +
In both cases, signals are re-scheduled with maximum priority and in the same order they were saved. +
This function is available only to agents and should be used only within transitions.#

To receive signals addressed to _pid=0_, the application must set a callback function using
the following:

[[set_receive_callback]]
* *set_receive_callback*([_callback_]) +
[small]#Sets the passed function as the application's receive callback for signals sent to _pid=0_. +
The callback is executed as *_callback(signal, sender)_*, where _sender_ is the _pid_ of
the agent that sent the _signal_, 
and it is required to <<dont_hang, return as soon as possible>> (no blocking calls).
If _callback_ is _nil_, any signal sent to the application will be silently discarded (default behavior). +
This function is available only to the application, and can be used at any time.#

