
== Special variables

IMPORTANT: In MoonAgents, *identifiers* composed of _one or more lower-case letters
and ending with an underscore_ (e.g., _$$self_$$_) are *reserved* for special variables.
Agent-scripts code *must not* set or change variables with such identifiers.

The *special variables* listed below are set in each agent's <<dedicated_env, $$_ENV$$>>,
when relevant:

* *_$$self_$$_*: the <<pid,pid>> of the agent itself.
* *_$$name_$$_*: the <<agent_name, name>> of the agent.
* *_$$parent_$$_*: the pid of the <<agent_hierarchy, parent>> agent.
* *_$$offspring_$$_*: the pid of the last child agent created by this one (or _nil_ if none).
* *_$$caller_$$_*: the pid of the original caller if the agent is a <<_procedures, procedure>> (or _nil_
if it is not).
* *_$$state_$$_*: the agent's current <<_agent_scripts, state>> (or _nil_ if the agent is stopping).

In addition, the following special variables are set before any transition is executed:

* *_$$signal_$$_*: the  <<_signals, signal>> that triggered the current transition.
* *_$$signame_$$_*: the signal name (same as _$$signal_$$[1]_).
* *_$$istimer_$$_*: _true_ if the signal was generated by a <<_timers,timer>>.
* *_$$sender_$$_*: the sender of the signal (pid, or tid if the signal was generated by a timer).
* *_$$sendtime_$$_*: the <<_system_time, point in time>> when the signal was sent.footnote:[
The *_$$sendtime_$$_* timestamp refers to the time when the signal was inserted in the internal
scheduler for dispatching: if the signal was sent with <<send, send>>(&nbsp;), this is when the
function was called;
for <<timers, timer-generated signals>>, it is the point in time the timer expiry was detected;
for <<time_triggered_signals, time-triggered signals>> it is the point in time the signal was
actually sent after its time ('_at_') had come.]
* *_$$recvtime_$$_*: the point in time when the signal was received.
* *_$$exptime_$$_*: the point in time when the signal becomes stale.

All special variables are to be considered *read-only*. Care should be taken not
to change their values from agent-script code.

